configfile: "config/config.yaml"


pepfile: config["pepfile"]


# Allow users to fix the underlying OS via singularity.
container: "docker://condaforge/mambaforge"


include: "rules/common.smk"


rule all:
    output:
        touch("hello.world"),
