configfile: "config/config.yaml"


pepfile: config["pepfile"]


# Allow users to fix the underlying OS via singularity.
container: "docker://condaforge/mambaforge"


include: "rules/common.smk"
include: "rules/ref.smk"


rule all:
    # input:
    # lambda wildcards: expand("resources/bibliographic_data/{file}.mrc.gz", file = get_filenames(wildcards))
    output:
        touch("do.nothing"),
